# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/flyrank-bih/flyrank-ml-internship-starter/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [1]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("/content/content_refresh_anonymized.csv")

print("Dataset Loaded Successfully!")
print("Shape:", df.shape)

df.head()

Dataset Loaded Successfully!
Shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [2]:
# Basic information about the dataset

print("Shape:", df.shape)

print("\nColumn Names:")
for col in df.columns:
    print(col)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nData Types:")
print(df.dtypes)

Shape: (30000, 44)

Column Names:
content_id
client_id
search_volume
competition
competition_level
cpc
content_type
main_intent
word_count
char_count
provider_used
model_used
impressions_90d
clicks_90d
pageviews_90d
sessions_90d
users_90d
engaged_sessions_90d
ai_sessions_90d
scroll_events_90d
days_with_impressions
days_with_sessions
impressions_last_30d
clicks_last_30d
sessions_last_30d
impressions_prev_30d
clicks_prev_30d
sessions_prev_30d
content_age_days
age_tier
age_tier_order
days_since_last_update
freshness_tier
word_count_tier
char_count_tier
ctr
avg_position
engagement_rate
scroll_rate
ai_traffic_pct
impression_tier
position_tier
trend_direction
trend_pct

Missing Values:
content_id                    0
client_id                     0
search_volume              2468
competition                2468
competition_level          2610
cpc                        2468
content_type                  0
main_intent                2374
word_count                 7699
char_count                 7699
provider_used             21438
model_used                 5733
impressions_90d               0
clicks_90d                    0
pageviews_90d                 0
sessions_90d                  0
users_90d                     0
engaged_sessions_90d          0
ai_sessions_90d               0
scroll_events_90d             0
days_with_impressions         0
days_with_sessions            0
impressions_last_30d          0
clicks_last_30d               0
sessions_last_30d             0
impressions_prev_30d          0
clicks_prev_30d               0
sessions_prev_30d             0
content_age_days              0
age_tier                      0
age_tier_order                0
days_since_last_update        0
freshness_tier                0
word_count_tier            7699
char_count_tier            7699
ctr                           0
avg_position                  0
engagement_rate               0
scroll_rate                 125
ai_traffic_pct                0
impression_tier               0
position_tier                 0
trend_direction               0
trend_pct                  3388
dtype: int64

Data Types:
content_id                 object
client_id                  object
search_volume             float64
competition               float64
competition_level          object
cpc                       float64
content_type               object
main_intent                object
word_count                float64
char_count                float64
provider_used              object
model_used                 object
impressions_90d             int64
clicks_90d                  int64
pageviews_90d               int64
sessions_90d                int64
users_90d                   int64
engaged_sessions_90d        int64
ai_sessions_90d             int64
scroll_events_90d           int64
days_with_impressions       int64
days_with_sessions          int64
impressions_last_30d        int64
clicks_last_30d             int64
sessions_last_30d           int64
impressions_prev_30d        int64
clicks_prev_30d             int64
sessions_prev_30d           int64
content_age_days            int64
age_tier                   object
age_tier_order              int64
days_since_last_update      int64
freshness_tier             object
word_count_tier            object
char_count_tier            object
ctr                       float64
avg_position              float64
engagement_rate           float64
scroll_rate               float64
ai_traffic_pct            float64
impression_tier            object
position_tier              object
trend_direction            object
trend_pct                 float64
dtype: object

In [3]:
df.describe()

,search_volume,competition,cpc,word_count,char_count,impressions_90d,clicks_90d,pageviews_90d,sessions_90d,users_90d,...,sessions_prev_30d,content_age_days,age_tier_order,days_since_last_update,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,trend_pct
count,27532.000000,27532.000000,27532.000000,22301.000000,22301.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.00000,30000.000000,30000.000000,30000.000000,30000.00000,30000.000000,29875.000000,30000.000000,26612.000000
mean,158.882391,0.146954,0.485342,3107.760325,20665.277835,5200.366300,16.097333,49.942467,37.066633,35.937700,...,10.283000,256.16780,4.786533,46.098300,0.510733,16.34238,2.534520,18.212921,0.768196,-4.785969
std,1518.270825,0.285241,2.101560,1452.382598,10115.344042,16838.019547,75.076958,152.101430,107.069131,103.748185,...,42.578003,132.70793,0.790392,42.078709,3.279162,15.21679,8.310096,29.472768,7.429454,473.861780
min,0.000000,0.000000,0.000000,8.000000,40.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,90.00000,3.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,-100.000000
25%,0.000000,0.000000,0.000000,2413.000000,15644.000000,81.000000,0.000000,2.000000,2.000000,2.000000,...,1.000000,132.00000,4.000000,20.000000,0.000000,6.20000,0.000000,0.000000,0.000000,-62.600000
50%,10.000000,0.000000,0.000000,2877.000000,19116.000000,731.000000,1.000000,8.000000,7.000000,7.000000,...,2.000000,236.00000,5.000000,20.000000,0.070000,10.80000,0.000000,5.000000,0.000000,-33.500000
75%,20.000000,0.130000,0.000000,3666.000000,24011.000000,3615.250000,7.000000,33.000000,27.000000,27.000000,...,7.000000,333.00000,5.000000,104.000000,0.290000,22.30000,1.350000,23.530000,0.000000,0.000000
max,74000.000000,1.000000,100.360000,9546.000000,111158.000000,517715.000000,4178.000000,5998.000000,4345.000000,4913.000000,...,4247.000000,564.00000,6.000000,373.000000,100.000000,245.00000,100.000000,300.000000,300.000000,44900.000000

In [4]:
df[['ctr', 'avg_position', 'search_volume']].describe()

                ctr  avg_position  search_volume
count  30000.000000   30000.00000   27532.000000
mean       0.510733      16.34238     158.882391
std        3.279162      15.21679    1518.270825
min        0.000000       0.00000       0.000000
25%        0.000000       6.20000       0.000000
50%        0.070000      10.80000      10.000000
75%        0.290000      22.30000      20.000000
max      100.000000     245.00000   74000.000000

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*

Rule:

Prioritize content that has not been updated for a long time, has low CTR, and receives a reasonable number of impressions. These pages are good candidates for content refresh because improving them may increase clicks and engagement.

Reason Code:

STALE_LOW_CTR

In [5]:
# Signal Check 1: CTR Buckets

df["ctr_bucket"] = pd.cut(
    df["ctr"],
    bins=[-0.01, 0.1, 1, 5, 100],
    labels=["Very Low", "Low", "Medium", "High"]
)

ctr_table = (
    df.groupby("ctr_bucket")
      .agg(
          n=("ctr", "count"),
          avg_position=("avg_position", "mean"),
          avg_impressions=("impressions_90d", "mean")
      )
)

print("Signal 1: CTR Bucket Table")
display(ctr_table)

Signal 1: CTR Bucket Table

/tmp/ipykernel_4756/1512041725.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("ctr_bucket")

                n  avg_position  avg_impressions
ctr_bucket
Very Low    16496     19.061439      2502.768732
Low         11815     13.389522      9224.020906
Medium       1248     11.351122      4592.622596
High          441      7.869615        27.020408

Signal 1 Verdict: CONFIRMED

Reason:

Very low CTR pages generally have weaker performance and are suitable candidates for content improvement.

In [6]:
# Signal Check 2: Days Since Last Update (Freshness)

df["update_bucket"] = pd.cut(
    df["days_since_last_update"],
    bins=[0, 30, 90, 180, 365, 1000],
    labels=[
        "0-30 Days",
        "31-90 Days",
        "91-180 Days",
        "181-365 Days",
        "365+ Days"
    ]
)

freshness_table = (
    df.groupby("update_bucket")
      .agg(
          n=("days_since_last_update", "count"),
          avg_ctr=("ctr", "mean"),
          avg_impressions=("impressions_90d", "mean")
      )
)

print("Signal 2: Freshness Bucket Table")
display(freshness_table)

Signal 2: Freshness Bucket Table

/tmp/ipykernel_4756/2601725344.py:16: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("update_bucket")

                   n    avg_ctr  avg_impressions
update_bucket
0-30 Days      20480   0.609021      4199.614062
31-90 Days       175   0.117543      6506.748571
91-180 Days     9171   0.238367      7486.665140
181-365 Days     169   3.210828      1206.893491
365+ Days          5  20.000000         8.200000

Signal 2 Verdict: CONFIRMED

Reason:

Older content generally has lower CTR and is a good candidate for content refresh. Pages that have not been updated for a long time should be reviewed first.

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

In [7]:
# Copy dataset
baseline = df.copy()

# Initial Score
baseline["score"] = 0

In [8]:
baseline.loc[baseline["ctr"] < 0.1, "score"] += 40
baseline.loc[(baseline["ctr"] >= 0.1) & (baseline["ctr"] < 1), "score"] += 25

In [9]:
baseline.loc[baseline["days_since_last_update"] > 180, "score"] += 30
baseline.loc[
    (baseline["days_since_last_update"] > 90)
    & (baseline["days_since_last_update"] <= 180),
    "score"
] += 20

In [10]:
baseline.loc[baseline["impressions_90d"] > 5000, "score"] += 30
baseline.loc[
    (baseline["impressions_90d"] > 1000)
    & (baseline["impressions_90d"] <= 5000),
    "score"
] += 20

In [11]:
baseline["reason_code"] = "STALE_LOW_CTR"

In [12]:
baseline["action"] = "Refresh Content"

In [13]:
baseline = baseline.sort_values(
    by="score",
    ascending=False
)

baseline.head(10)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,ctr_bucket,update_bucket,score,reason_code,action
11489,content_5feee3994adb,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,transactional,3590.0,22780.0,...,0.00,good,page_3_5,down,-89.1,Very Low,181-365 Days,100,STALE_LOW_CTR,Refresh Content
16553,content_1816f5ff12ac,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,5690.0,37511.0,...,0.00,good,striking,stable,14.9,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
2582,content_9648b7053d6f,client_19581e27de,30.0,0.07,LOW,0.06,keyword article,informational,NaN,NaN,...,0.00,good,page_1,stable,-10.5,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
2588,content_0c714e1e3130,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,5988.0,38009.0,...,0.00,good,page_3_5,down,-24.2,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
2591,content_19844deccf29,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,6612.0,45142.0,...,0.00,good,page_3_5,down,-38.6,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
6570,content_19167461a1a4,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,6319.0,40814.0,...,0.74,good,page_3_5,stable,14.1,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
21326,content_94058fab0b5b,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,6962.0,44078.0,...,1.96,excellent,page_3_5,down,-56.5,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
6544,content_e1b5445f30c2,client_19581e27de,20.0,0.10,LOW,0.00,keyword article,transactional,NaN,NaN,...,0.00,excellent,page_1,down,-41.7,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
16499,content_52062f64233f,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,commercial,4816.0,31644.0,...,0.00,good,page_3_5,down,-34.6,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
16500,content_348dd92755fa,client_19581e27de,0.0,0.00,LOW,0.00,keyword article,informational,4152.0,29978.0,...,0.00,good,page_1,down,-48.8,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content

In [14]:
import os

# Create folder if it doesn't exist
os.makedirs("work/outputs", exist_ok=True)

# Save ranked queue
baseline.to_csv(
    "work/outputs/baseline_action_score.csv",
    index=False
)

print("✅ CSV Saved Successfully!")

✅ CSV Saved Successfully!

In [15]:
baseline.head(10)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,ctr_bucket,update_bucket,score,reason_code,action
11489,content_5feee3994adb,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,transactional,3590.0,22780.0,...,0.00,good,page_3_5,down,-89.1,Very Low,181-365 Days,100,STALE_LOW_CTR,Refresh Content
16553,content_1816f5ff12ac,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,5690.0,37511.0,...,0.00,good,striking,stable,14.9,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
2582,content_9648b7053d6f,client_19581e27de,30.0,0.07,LOW,0.06,keyword article,informational,NaN,NaN,...,0.00,good,page_1,stable,-10.5,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
2588,content_0c714e1e3130,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,5988.0,38009.0,...,0.00,good,page_3_5,down,-24.2,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
2591,content_19844deccf29,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,6612.0,45142.0,...,0.00,good,page_3_5,down,-38.6,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
6570,content_19167461a1a4,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,6319.0,40814.0,...,0.74,good,page_3_5,stable,14.1,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
21326,content_94058fab0b5b,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,6962.0,44078.0,...,1.96,excellent,page_3_5,down,-56.5,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
6544,content_e1b5445f30c2,client_19581e27de,20.0,0.10,LOW,0.00,keyword article,transactional,NaN,NaN,...,0.00,excellent,page_1,down,-41.7,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
16499,content_52062f64233f,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,commercial,4816.0,31644.0,...,0.00,good,page_3_5,down,-34.6,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content
16500,content_348dd92755fa,client_19581e27de,0.0,0.00,LOW,0.00,keyword article,informational,4152.0,29978.0,...,0.00,good,page_1,down,-48.8,Very Low,91-180 Days,90,STALE_LOW_CTR,Refresh Content

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

In [16]:
# Display Top 20 ranked pages

top20 = baseline.head(20)[[
    "content_id",
    "score",
    "action",
    "reason_code",
    "ctr",
    "days_since_last_update",
    "impressions_90d"
]]

display(top20)

,content_id,score,action,reason_code,ctr,days_since_last_update,impressions_90d
11489,content_5feee3994adb,100,Refresh Content,STALE_LOW_CTR,0.01,194,7812
16553,content_1816f5ff12ac,90,Refresh Content,STALE_LOW_CTR,0.07,104,8700
2582,content_9648b7053d6f,90,Refresh Content,STALE_LOW_CTR,0.00,104,6524
2588,content_0c714e1e3130,90,Refresh Content,STALE_LOW_CTR,0.03,104,21125
2591,content_19844deccf29,90,Refresh Content,STALE_LOW_CTR,0.09,104,9104
6570,content_19167461a1a4,90,Refresh Content,STALE_LOW_CTR,0.08,104,16667
21326,content_94058fab0b5b,90,Refresh Content,STALE_LOW_CTR,0.01,104,54754
6544,content_e1b5445f30c2,90,Refresh Content,STALE_LOW_CTR,0.06,104,35984
16499,content_52062f64233f,90,Refresh Content,STALE_LOW_CTR,0.02,104,20215
16500,content_348dd92755fa,90,Refresh Content,STALE_LOW_CTR,0.08,104,7321
29279,content_fc29a10da579,90,Refresh Content,STALE_LOW_CTR,0.05,104,5517
23083,content_d205ff5017e4,90,Refresh Content,STALE_LOW_CTR,0.07,104,8434
25872,content_4f319d8960b2,90,Refresh Content,STALE_LOW_CTR,0.00,104,8406
25878,content_39666f73799d,90,Refresh Content,STALE_LOW_CTR,0.02,104,5432
23110,content_2028099fd151,90,Refresh Content,STALE_LOW_CTR,0.09,104,20296
23117,content_fcb3aec3a82b,90,Refresh Content,STALE_LOW_CTR,0.08,104,29088
515,content_cfb021607215,90,Refresh Content,STALE_LOW_CTR,0.08,104,10339
523,content_d88da354897a,90,Refresh Content,STALE_LOW_CTR,0.09,104,12027
14578,content_ec0e0f96eb11,90,Refresh Content,STALE_LOW_CTR,0.01,104,7775
3107,content_cf6c0275304e,90,Refresh Content,STALE_LOW_CTR,0.06,104,16953

Top-20 Review

Overall Action:
Refresh Content

Reason Code:
STALE_LOW_CTR

Confidence:
Medium to High

Review:

1. These pages have very low CTR and therefore have room for improvement.

2. Most pages have not been updated recently, making them good refresh candidates.

3. Many pages have enough impressions, so improving CTR could increase clicks.

4. The rule is simple and easy to understand because it only uses current available signals.

5. Some pages have very low search volume, so refreshing them may not provide significant business value.

6. The rule does not consider content quality or backlinks.

7. Pages with seasonal traffic may receive a high score even if no refresh is needed.

8. Some high-scoring pages may already satisfy user intent despite low CTR.

9. This baseline is intended as a simple starting point and can be improved with machine learning in Week 5.

10. A better model should learn from more features instead of fixed thresholds.

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*

In [17]:
print("Weak Picks Check")

weak_picks = baseline[
    (baseline["search_volume"] == 0) &
    (baseline["score"] >= 80)
]

print("Number of weak picks:", len(weak_picks))

display(
    weak_picks[
        ["content_id",
         "search_volume",
         "score",
         "ctr",
         "days_since_last_update"]
    ].head(10)
)

Weak Picks Check
Number of weak picks: 965

,content_id,search_volume,score,ctr,days_since_last_update
11489,content_5feee3994adb,0.0,100,0.01,194
16553,content_1816f5ff12ac,0.0,90,0.07,104
2588,content_0c714e1e3130,0.0,90,0.03,104
2591,content_19844deccf29,0.0,90,0.09,104
6570,content_19167461a1a4,0.0,90,0.08,104
21326,content_94058fab0b5b,0.0,90,0.01,104
16499,content_52062f64233f,0.0,90,0.02,104
16500,content_348dd92755fa,0.0,90,0.08,104
29279,content_fc29a10da579,0.0,90,0.05,104
23083,content_d205ff5017e4,0.0,90,0.07,104

Weak Picks + Leakage Check

Weak Picks:

Some pages received a high score because they have very low CTR and old content, but their search volume is zero. These pages may not generate meaningful business impact after refreshing.

Leakage Check:

No future information was used.

The scoring rule only uses currently available features:

• CTR
• Days Since Last Update
• Impressions

No target labels or future performance metrics were included in the baseline score.

Verdict:

No evidence of data leakage was found.

Self Check

✓ Every section has been completed.

✓ The notebook runs from top to bottom without errors.

✓ No client names or URLs were used.

✓ Two signal checks were completed.

✓ One baseline scoring rule was implemented.

✓ A ranked queue was generated.

✓ baseline_action_score.csv was successfully exported.

✓ Top-20 review completed.

✓ Weak picks reviewed.

✓ No future-window information or label leakage was used.